apiVersion: v2
name: harmony
description: A Helm chart for Kubernetes
type: application
version: "0.1.0"
appVersion: "0.0.4"
kubeVersion: ">1.31.0"
sources: 
  - "https://github.com/gpuslave/harmony-go"
maintainers:
  - name: gpuslave
    url: https://github.com/gpuslave